### ISSUE TITLE
publish that on crates.io

### ISSUE THREAD

**Issue by alexmyczko** [huxingyi/meshlite#10]
can you put that on crates.io ?

**Comment by huxingyi** [comment]
Hi, thanks for your kind remind, what stops me putting on crates.io is that, it was only been used in Dust3D, and the APIs continue to change to satisfy the need of Dust3D. I guess current is a good time point to move to crates.io, because most of the APIs are stable now. Will do it in recent. Thanks!

**Comment by alexmyczko** [comment]
Thanks a lot, reason for that would be to get dust3d packaged for Debian (and Ubuntu gets the copy for free)

**Comment by huxingyi** [comment]
Currently I am using the AppImage to do the beta release for linux, I don't know how Debian package works, but sounds pretty cool, thanks.

**Comment by huxingyi** [comment]
Hi @alexmyczko just to let you know, both [meshlite](https://crates.io/crates/meshlite) and [meshlite_ffi](https://crates.io/crates/meshlite_ffi) are on crates.io now. Dust3D is not using meshlite directly, but use the C api layer: meshlite_ffi 
Although I am not familiar with Debian package, if you need any help on packaging Dust3D, please let me know, thanks.

**Comment by probonopd** [comment]
> Currently I am using the AppImage to do the beta release for linux

Where can the AppImage be downloaded? Thanks.

**Comment by huxingyi** [comment]
Hi @probonopd we are talking Dust3D, a 3D modeler which use meshlite as a library. You helped me testing it several months ago. AppImage works like a charm, thank you! Here is the latest release of Dust3D: 
https://github.com/huxingyi/dust3d/releases/tag/1.0.0-beta.13
meshlite as a library don’t need a release for Linux yet.

**Comment by probonopd** [comment]
Indeed we are already promoting it on https://appimage.github.io/Dust3D/
Thank you very much :+1:
